services:
  app:
    build:
      context: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5431"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

