services:
  app:
    build:
      context: ./backend
    container_name: laravelBackend
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginxServer
    volumes:
      - ./backend:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vueFrontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

